name: End to End Tests Flink 1.16

on: [push, pull_request]

jobs:
  code-style:
    if: github.repository == 'apache/incubator-paimon'
    name: Code style
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Check code style
        run: ./mvnw --batch-mode --quiet --no-snapshot-updates clean spotless:check

  build:
    runs-on: ubuntu-latest
    needs: [ code-style ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Flink 1.16
        run: ./mvnw clean install -DskipTests
      - name: Test Flink 1.16
        run: |
          # run tests with random timezone to find out timezone related bugs
          . .github/workflows/utils.sh
          jvm_timezone=$(random_timezone)
          echo "JVM timezone is set to $jvm_timezone"
          ./mvnw test -pl paimon-e2e-tests -Duser.timezone=$jvm_timezone
