################################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

name: UTCase and ITCase Others on JDK 11

on:
  issue_comment:
    types: [created, edited, deleted]

  # daily run
  schedule:
    - cron: "0 0 * * *"

env:
  JDK_VERSION: 11

jobs:
  build:
    if: |
      github.event_name == 'schedule' ||
      (contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/jdk11'))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: 'adopt'
      - name: Build
        run:  mvn -T 1C -B clean install -DskipTests
      - name: Test
        run: |
          # run tests with random timezone to find out timezone related bugs
          . .github/workflows/utils.sh
          jvm_timezone=$(random_timezone)
          echo "JVM timezone is set to $jvm_timezone"
          test_modules="!paimon-e2e-tests,!org.apache.paimon:paimon-hive-connector-3.1,"
          for suffix in 3.5 3.4 3.3 3.2 common; do
          test_modules+="!org.apache.paimon:paimon-spark-${suffix},"
          done
          test_modules="${test_modules%,}"
          mvn -T 1C -B clean install -pl "${test_modules}" -Pskip-paimon-flink-tests -Duser.timezone=$jvm_timezone
        env:
          MAVEN_OPTS: -Xmx4096m